version: 8.1.3-aci-{build}
image: Visual Studio 2017 RC
environment:
  CLI_VERSION: 1.0.0-rc4-004842

build_script:
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: dotnet build -c Release --version-suffix "aci-${env:APPVEYOR_BUILD_NUMBER}"
  - ps: dotnet test -c Release tests/Aether.Tests/Aether.Tests.fsproj
  - ps: dotnet pack -c Release --include-symbols --version-suffix "aci-${env:APPVEYOR_BUILD_NUMBER}"

test: off

artifacts:
  - path: '**\*.nupkg'
